// flow-typed signature: b4fda1ec00c89aee35a5f58e75ad8cf1
// flow-typed version: <<STUB>>/rebass_v^4.0.7/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebass/dist/index.esm' {
  declare module.exports: any;
}

declare module 'rebass/dist' {
  declare module.exports: any;
}

declare module 'rebass/src' {
  declare module.exports: any;
}

declare module 'rebass/styled-components' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebass/dist/index.esm.js' {
  declare module.exports: $Exports<'rebass/dist/index.esm'>;
}
declare module 'rebass/dist/index' {
  declare module.exports: $Exports<'rebass/dist'>;
}
declare module 'rebass/dist/index.js' {
  declare module.exports: $Exports<'rebass/dist'>;
}
declare module 'rebass/src/index' {
  declare module.exports: $Exports<'rebass/src'>;
}
declare module 'rebass/src/index.js' {
  declare module.exports: $Exports<'rebass/src'>;
}
declare module 'rebass/styled-components/index' {
  declare module.exports: $Exports<'rebass/styled-components'>;
}
declare module 'rebass/styled-components/index.js' {
  declare module.exports: $Exports<'rebass/styled-components'>;
}
