// flow-typed signature: 23626646da32aa379a473f8dca9c5ae4
// flow-typed version: <<STUB>>/@rebass/preset_v^4.0.5/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rebass/preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rebass/preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rebass/preset/dist' {
  declare module.exports: any;
}

declare module '@rebass/preset/src' {
  declare module.exports: any;
}

declare module '@rebass/preset/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rebass/preset/dist/index' {
  declare module.exports: $Exports<'@rebass/preset/dist'>;
}
declare module '@rebass/preset/dist/index.js' {
  declare module.exports: $Exports<'@rebass/preset/dist'>;
}
declare module '@rebass/preset/src/index' {
  declare module.exports: $Exports<'@rebass/preset/src'>;
}
declare module '@rebass/preset/src/index.js' {
  declare module.exports: $Exports<'@rebass/preset/src'>;
}
declare module '@rebass/preset/test/index' {
  declare module.exports: $Exports<'@rebass/preset/test'>;
}
declare module '@rebass/preset/test/index.js' {
  declare module.exports: $Exports<'@rebass/preset/test'>;
}
